name: Deploy Laravel Project to GitHub Pages

on:
  push:
    branches:
      - main # Change to your default branch name if it's not 'main'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4' # or your Laravel PHP version

      - name: Install Composer dependencies
        run: composer install --no-progress --prefer-dist --optimize-autoloader

      - name: Run migrations
        run: php artisan migrate --force
        env:
          DB_CONNECTION: sqlite
          DB_DATABASE: /tmp/database.sqlite

      - name: Set up database
        run: |
          touch /tmp/database.sqlite
          php artisan migrate --force
        env:
          DB_CONNECTION: sqlite
          DB_DATABASE: /tmp/database.sqlite

      - name: Build assets
        run: npm install && npm run production

      - name: Deploy to GitHub Pages
        run: |
          mkdir public/static
          mv public/* public/static/
          cp -r public/static/* .
          rm -r public/static
          touch .nojekyll
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
